version: '3.6' 

services:
  registry:
    build: ./registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml
  web:
    image: hyper/docker-registry-web
    ports:
      - "5001:8080"
    volumes:
      - ./web/config.yml:/conf/config.yml





# https://hub.docker.com/r/hyper/docker-registry-web
# https://github.com/mkuchin/docker-registry-web
# https://github.com/mkuchin/docker-registry-web/blob/master/web-app/WEB-INF/config.yml


# docker-compose exec registry sh
# cd /var/lib/registry
  # watch -n 1 -d tree -L 4 docker/registry/v2/
# docker image push localhost:5000/busybox # create directories:
# cd /var/lib/registry/docker/registry/v2
  # tree -L 4
  # watch -n1 ls -al 'repositories/**/_uploads'
  # push mongo (big so takes time, kill in middle if you want and see stuff left behind)
# curl -X DELETE 'http://localhost:5000/v2/busybox/manifests/sha256:186694df7e479d2b8bf075d9e1b1d7a884c6de60470006d572350573bfa6dcd2'