version: "3.5"

services:
  vetted-registry:
    image: registry:2.6.2
    ports: 
      - "55000:5000"
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
  requestbin:
    image: weshigbee/requestbin
    ports:
      - "8000:8000"
